#================================ mysql ======================================
#  mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  name: shuyuxuan
  user: zhangshuyu
  password: 654321
# 百度翻译
translate:
  appid: 20210727000899584
  secret: ofYIh1a5qfWw3FAnpNBS