#================================ mysql ======================================
#  mysql配置
mysql:
  host: 118.25.228.199
  port: 3306
  name: shuyuxuan_test
  user: zhangshuyu
  password: 654321
# 百度翻译
translate:
  appid: 20210727000899584
  secret: ofYIh1a5qfWw3FAnpNBS
